version: '2'

services:
  matching-engine:
      build: ./src/matching-engine
      volumes:
        - ./src/matching-engine:/code
      ports:
        - "12345:12345" #bind port 12345 of current machine to 12345 in container
      command: sh -c "make all && ./main"

  db:
